### ISSUE TITLE
'as_cholmod_sparse' not provided by package 'Matrix'

### ISSUE THREAD

**Issue by IENAUMANN** [kharchenkolab/pagoda2#145]
when I run the following code: 
> pbmc.data <- Read10X(data.dir = data.path)
> p2.processed <- basicP2proc(pbmc.data, n.cores=1, min.cells.per.gene=10, 
+                     n.odgenes=2e3, get.largevis=FALSE, make.geneknn=FALSE)
, I always get this error:
Error in irlba(x, nv = nPcs, nu = 0, center = cm, right_only = FALSE,  : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'. I tried to resolve it by installing previous versions of irlba, and matrix and also installed the RSpectra package as described by others but it seems to be pagoda2 specific because I don't get this error when using any other function. Any idea what could cause the issue?

**Comment by evanbiederstedt** [comment]
It looks like others are having this issue: https://github.com/cole-trapnell-lab/monocle3/issues/690

I'll try to write a stable fix when I have time

**Comment by evanbiederstedt** [comment]
Thanks for the issue @IENAUMANN 

Basically, the problem is here: https://github.com/bwlewis/irlba/issues/70

The maintainers of `irlba` will be the ones to fix this. I'm pretty sure they will at some point. 

There's nothing for us to do until wait for them to fix this. It is what it is, I'm afraid.
