### ISSUE TITLE
Reproducibility Question 

### ISSUE THREAD

**Issue by katkatrach** [kharchenkolab/pagoda2#148]
Hello!

I am using Pagoda2 for the clustering steps in analyzing my sc data. I've noticed that running makeKnnGraph and getKnnClusters will produce different cluster counts when ran on the same Pagoda2 object in different sessions. I do set.seed at the beginning of each session. Are there any parameters for these functions that can ensure reproducibility?

Thank you for any insight!

**Comment by evanbiederstedt** [comment]
Hi @katkatrach 

It's a good question; there's a way to set the seed somehow, but it's been some time since I've looked at this. If memory serves me right, it's based on this: https://github.com/kharchenkolab/N2R

There's a related discussion here: https://github.com/kharchenkolab/leidenAlg/pull/17

We're happy to look at pull requests. I think the seed needs to be set with the C++ code, not within R. 

Best, Evan
