### ISSUE TITLE
biomaRt custom annotation

### ISSUE THREAD

**Issue by TsukasaKo** [kharchenkolab/pagoda2#18]
I would like to use custom annotation with BioMart to 10x genomics data on PAGODA2 walkthrough.
Tutorial uses GO number with below commands however I want  to see with GO annotation on browser.

I just did 

> library(biomaRt)
> library(GO.db)
> ensembl <- useMart("ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl", host="www.ensembl.org")
> go <- getBM(attributes = c("hgnc_symbol", "go_id"), filters = "hgnc_symbol", values = rownames(counts), mart = ensembl)
> go$term <- Term(go$go_id)
> s = split(go$hgnc_symbol, paste(go$go_id,go$term))
> go.env <- list2env(s)
>r$testPathwayOverdispersion(go.env,verbose=T,correlation.distance.threshold=0.95,recalculate.pca=F,top.aspects=15)

However after app command, below error appeared.

> app <- p2.make.pagoda1.app(r,go.env,inner.clustering=TRUE,embeddingType='tSNE',clusterType='community',min.group.size=1)
Error in mget(df$name, GO.db::GOTERM, ifnotfound = NA) : 
  second argument must be an environment

If you can help me, this is really appreciated.

**Comment by barkasn** [comment]
Hi TsukasaKo: The error most likely occurs because the structure of the go.env is not what is expected. I would have to look into the object into detail to be able to help you with this. p2.make.pagoda1.app makes the old style web apps and will be gradually phased out, could you try to see if you get the same error if you try to make the newer style app?

**Comment by barkasn** [comment]
@evanbiederstedt I don't think this is an issue anymore as long as the current tutorial works. Feel free to close
