### ISSUE TITLE
web app doesn't show GO pathways related to aspects

### ISSUE THREAD

**Issue by elimereu** [kharchenkolab/pagoda2#54]
Hi,

I've finally try to run Pagoda2. I like it and I find the web app really helpful! 
Especially this new interactive version looks promising. 
However, I remember in pagoda 1, it was nice to see GOs related to each aspects, while now I can only 
see these numbers, which is not clear to me what they are.. 
In the example bin file you prepared looks like in the attached screenshot: 

![screen shot 2018-07-23 at 17 34 05](https://user-images.githubusercontent.com/20638667/43086914-d1e7703c-8e9e-11e8-8a97-f0a84f02f0a8.png)

Also I'm not sure about the meaning of white parts in the heatmaps with aspects. 

Any helps will be really appreciated! 

Thanks a lot, 

Elisabetta

**Comment by barkasn** [comment]
Hi elimereu,

The aspects panel has been replaced by contrasts between clusters in a walk down the cluster tree. This was done because generating the GO-based aspects typically takes a very long time with the number of cells we are dealing with today.

It is however possible to calculate the old-style aspects by replacing the call to getHierarchicalDiffExpressionAspects() with testPathwayOverdispersion(), which is similar to the old function. Both functions set the matrix of over-dispersed pathways in misc[['pathwayOD']] of the pagoda2 object, so running both will result in the latest results overwriting the previous ones. You will also need to generate GO gene sets and add the to the web custom sets using the provided function: 

goSets <- p2.generate.human.go.web(myGeneNames)

for human (mouse and zebrafish functions are also provided in "R/pagodaWebHelpers.R"

Please let me know if you run into problems getting this to work.

Nick

**Comment by haircell** [comment]
Hi, 

I'm also trying to implement the "old method" using `testPathwayOverdispersion()`. I'm working with a SmartSeq2 data set that's only a few hundred cells, so computationally, it should still be ok. I'm able to run the following without issues:

```
hdea <- r$getHierarchicalDiffExpressionAspects(type='PCA', clusterName='community',z.threshold=3)

# prep geneset for web app
genesets <- hierDiffToGenesets(hdea)
str(genesets[1:2])

# Add GO Terms as genesets:
library(GO.db)
termDescriptions <- Term(GOTERM[names(go.env)]) 
sn <- function(x) { names(x) <- x; x}
genesets.go <- lapply(sn(names(go.env)),function(x) {
  list(properties=list(locked=T,genesetname=x,
                       shortdescription=as.character(termDescriptions[x])),
       genes=c(go.env[[x]]))
})

genesets <- c(genesets, genesets.go)
deSets <- get.de.geneset(r, groups = r$clusters$PCA[['community']], prefix = 'de_')
genesets <- c(genesets, deSets)
```

Instead of the first line above, I'd like to run this as you suggest. This runs ok, but how do I prep the geneset for the web app?  Is there a function equivalent to `hierDiffToGenesets()` for PathwayOverdispersion that I'm missing? 
```
path.OD <- r$testPathwayOverdispersion(go.env,verbose=T,correlation.distance.threshold=0.95,
                         recalculate.pca=F,top.aspects=15)
```

Thanks!

**Comment by ccruizm** [comment]
Hello! I would also like to view the Gene sets related to each cluster and not just a long list with all the GO terms. I have called `r$testPathwayOverdispersion(go.env,verbose=T,correlation.distance.threshold=0.95,recalculate.pca=F,top.aspects=15)` and then `r$getHierarchicalDiffExpressionAspects(type='PCA',clusterName='community',z.threshold=3)` as is mentioned in the tutorial. However, isn't clear for me where and how I can add `goSets <- p2.generate.human.go.web(myGeneNames)` as you previously explained @barkasn to show the GO terms by cluster/multilevel. Thanks in advance for your help.

**Comment by barkasn** [comment]
@evanbiederstedt I think this is fixed, but we should make sure that it works well with the tutorials
